### ISSUE TITLE
Slatwall error when exporting class extensions in mura 6.2

### ISSUE THREAD

**Issue by dbarth-aca** [ten24/slatwall#4237]
There is a feature in Mura 6.2 that allows you to export class extensions. Unfortunately I get the following error from Slatwall when I attempt this. 
slatwall 4.3.011
mura 6.2.6525

---
#500 Error
## failed to lazily initialize a collection of role: SlatwallAccount.accountLoyalties, no session or session was closed

Type: org.hibernate.LazyInitializationException 

 org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: SlatwallAccount.accountLoyalties, no session or session was closed
    at org.hibernate.collection.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:380)
    at org.hibernate.collection.AbstractPersistentCollection.throwLazyInitializationExceptionIfNotConnected(AbstractPersistentCollection.java:372)
    at org.hibernate.collection.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:119)
    at org.hibernate.collection.PersistentBag.size(PersistentBag.java:248)
    at coldfusion.runtime.ObjectDuplicator.duplicateList(ObjectDuplicator.java:179)
    at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:99)
    at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
    at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2553)
    at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2528)
    at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)
    at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
    at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2553)
    at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2528)
    at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)
    at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
    at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2553)
    at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2528)
    at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)
    at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
    at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2553)
    at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2527)
    at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)
    at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
    at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2553)
    at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2527)
    at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)
    at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
    at coldfusion.runtime.Struct.duplicate(Struct.java:152)
    at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:102)
    at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
    at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2553)
    at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2528)
    at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)
    at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
    at coldfusion.runtime.Struct.duplicate(Struct.java:152)
    at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:102)
    at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
    at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2553)
    at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2528)
    at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)
    at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
    at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2553)
    at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2528)
    at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)
    at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
    at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2553)
    at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2528)
    at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)
    at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
    at coldfusion.runtime.Struct.duplicate(Struct.java:152)
    at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:102)
    at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
    at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2553)
    at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2528)
    at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)
    at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
    at coldfusion.runtime.Struct.duplicate(Struct.java:152)
    at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:102)
    at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
    at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2553)
    at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2528)
    at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)
    at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
    at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2553)
    at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2527)
    at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)
    at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
    at coldfusion.runtime.TemplateProxy.duplicateScope(TemplateProxy.java:2553)
    at coldfusion.runtime.TemplateProxy.duplicate(TemplateProxy.java:2528)
    at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:125)
    at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
    at coldfusion.runtime.Array.Duplicate(Array.java:105)
    at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:90)
    at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
    at coldfusion.runtime.Struct.duplicate(Struct.java:152)
    at coldfusion.runtime.ObjectDuplicator._duplicate(ObjectDuplicator.java:102)
    at coldfusion.runtime.ObjectDuplicator.duplicate(ObjectDuplicator.java:78)
    at coldfusion.runtime.CFPage.Duplicate(CFPage.java:5872)
    at cfextendSet2ecfc277498028$funcGETASXML.runFunction(C:\Sites\test.org\requirements\mura\extend\extendSet.cfc:456)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
    at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:405)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:655)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:444)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:414)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2428)
    at cfextendSubType2ecfc1999523771$funcGETASXML.runFunction(C:\Sites\test.org\requirements\mura\extend\extendSubType.cfc:924)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
    at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:405)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:655)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:444)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:414)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2428)
    at cfextendManager2ecfc1761092377$funcGETSUBTYPESASXML.runFunction(C:\Sites\test.org\requirements\mura\extend\extendManager.cfc:1651)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:655)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:444)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:414)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2428)
    at cfcextend2ecfc632022440$funcEXPORT.runFunction(C:\Sites\test.org\admin\core\controllers\cextend.cfc:112)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
    at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:518)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:660)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:469)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2369)
    at coldfusion.tagext.lang.InvokeTag.doEndTag(InvokeTag.java:402)
    at cfframework2ecfc419957465$funcDOCONTROLLER.runFunction(C:\Sites\test.org\admin\framework.cfc:1308)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
    at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2655)
    at cfframework2ecfc419957465$funcONREQUEST.runFunction(C:\Sites\test.org\admin\framework.cfc:517)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:655)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:444)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:414)
    at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:108)
    at coldfusion.runtime.AppEventInvoker.onRequest(AppEventInvoker.java:300)
    at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:426)
    at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:48)
    at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
    at coldfusion.filter.PathFilter.invoke(PathFilter.java:112)
    at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:30)
    at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
    at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
    at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
    at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:58)
    at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
    at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
    at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
    at coldfusion.CfmServlet.service(CfmServlet.java:219)
    at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
    at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:437)
    at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:197)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)

Column: 0
ID: CF_CFPAGE
Line: 456
Raw Trace: at cfextendSet2ecfc277498028$funcGETASXML.runFunction(C:\Sites\test.org\requirements\mura\extend\extendSet.cfc:456)
Template: C:\Sites\test.org\requirements\mura\extend\extendSet.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 924
Raw Trace: at cfextendSubType2ecfc1999523771$funcGETASXML.runFunction(C:\Sites\test.org\requirements\mura\extend\extendSubType.cfc:924)
Template: C:\Sites\test.org\requirements\mura\extend\extendSubType.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 1651
Raw Trace: at cfextendManager2ecfc1761092377$funcGETSUBTYPESASXML.runFunction(C:\Sites\test.org\requirements\mura\extend\extendManager.cfc:1651)
Template: C:\Sites\test.org\requirements\mura\extend\extendManager.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 112
Raw Trace: at cfcextend2ecfc632022440$funcEXPORT.runFunction(C:\Sites\test.org\admin\core\controllers\cextend.cfc:112)
Template: C:\Sites\test.org\admin\core\controllers\cextend.cfc
Type: CFML

Column: 0
ID: CFINVOKE
Line: 1308
Raw Trace: at cfframework2ecfc419957465$funcDOCONTROLLER.runFunction(C:\Sites\test.org\admin\framework.cfc:1308)
Template: C:\Sites\test.org\admin\framework.cfc
Type: CFML

Column: 0
ID: CF_UDFMETHOD
Line: 517
Raw Trace: at cfframework2ecfc419957465$funcONREQUEST.runFunction(C:\Sites\test.org\admin\framework.cfc:517)
Template: C:\Sites\test.org\admin\framework.cfc
Type: CFML

**Comment by gregmoser** [comment]
Looks like this is getting hung up on the following line:
https://github.com/blueriver/MuraCMS/blob/develop/requirements/mura/extend/extendSet.cfc#L456

where it is calling the `duplicate(variables.instance)`, and my guess is that variables.instance has some type of persistent entity in it.  Can you do a writeDump(var=variables.instance, top=3, abort=true);

-G

**Comment by dbarth-aca** [comment]
Hi Greg-
This is **writeDump(var=variables.instance, top=3, abort=true);** from **extendSet.cfc#L456**
http://screencast.com/t/bAbCGW70H

**Comment by gregmoser** [comment]
Well, that is very strange.  I'm not sure why duplicate() isn't working.  If you restart the server you still get this error?

**Comment by dbarth-aca** [comment]
Restarted the server and I still receive this error.

**Comment by gregmoser** [comment]
Lets try this:
writeDump(var=variables.instance.attributes[1], top=3, abort=true);

I'm wondering if there are any ORM objects in the attribute object.
