### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by peterHID** [ten24/slatwall#5365]
I am running mura 7 and tried to install slatwall via plugin and received this error. Hostek is the hosting company

Thanks

Peter

500 Error
Type: java.lang.IllegalArgumentException 
 java.lang.IllegalArgumentException
	at sun.reflect.GeneratedConstructorAccessor4026.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at sun.reflect.GeneratedMethodAccessor760.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at coldfusion.runtime.StructBean.invoke(StructBean.java:508)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2553)
	at cfJavaProxy2ecfc337695686$funcINIT.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\antisamy\lib\javaloader\JavaProxy.cfc:67)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483)
	at cfJavaLoader2ecfc287609260$funcINIT.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\antisamy\lib\javaloader\JavaLoader.cfc:69)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483)
	at cfHibachiUtilityService2ecfc1855791383._factor0(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\HibachiUtilityService.cfc:18)
	at cfHibachiUtilityService2ecfc1855791383._factor18(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\HibachiUtilityService.cfc:5)
	at cfHibachiUtilityService2ecfc1855791383.runPage(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\HibachiUtilityService.cfc:1)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:246)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.TemplateProxyFactory.resolveComponentHelper(TemplateProxyFactory.java:538)
	at coldfusion.runtime.TemplateProxyFactory.resolveName(TemplateProxyFactory.java:248)
	at coldfusion.runtime.TemplateProxyFactory.resolveComponentHelper(TemplateProxyFactory.java:374)
	at coldfusion.runtime.TemplateProxyFactory.resolveName(TemplateProxyFactory.java:248)
	at coldfusion.runtime.TemplateProxyFactory.resolveName(TemplateProxyFactory.java:159)
	at coldfusion.runtime.TemplateProxyFactory.resolveName(TemplateProxyFactory.java:149)
	at coldfusion.cfc.ComponentProxyFactory.getProxy(ComponentProxyFactory.java:57)
	at coldfusion.runtime.CFPage.CreateObject(CFPage.java:5976)
	at coldfusion.runtime.CFPage.CreateObject(CFPage.java:5991)
	at cfioc2ecfc617699991$funcCACHABLE.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\DI1\ioc.cfc:198)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2854)
	at cfioc2ecfc617699991$funcRESOLVEBEANCREATE.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\DI1\ioc.cfc:464)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2854)
	at cfioc2ecfc617699991$funcRESOLVEBEANCREATE.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\DI1\ioc.cfc:494)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2854)
	at cfioc2ecfc617699991$funcRESOLVEBEAN.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\DI1\ioc.cfc:438)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2854)
	at cfioc2ecfc617699991$funcGETBEAN.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\DI1\ioc.cfc:80)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483)
	at cfHibachiObject2ecfc1720666238$funcGETBEAN.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\HibachiObject.cfc:34)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2854)
	at cfHibachiObject2ecfc1720666238$funcGETSERVICE.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\HibachiObject.cfc:40)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483)
	at cfHibachi2ecfc1314475297$funcVERIFYAPPLICATIONSETUP.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\Hibachi.cfc:647)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2854)
	at cfHibachi2ecfc1314475297$funcSETUPGLOBALREQUEST.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\Hibachi.cfc:211)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483)
	at cfHandler2ecfc1562055548$funcVERIFYSLATWALLREQUEST.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\integrationServices\mura\model\handler\Handler.cfc:73)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:533)
	at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2819)
	at cfMuraEventHandler2ecfc1759258189$funcONGLOBALREQUESTSTART.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\integrationServices\mura\model\handler\MuraEventHandler.cfc:494)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:420)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:533)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:648)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:457)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2424)
	at coldfusion.tagext.lang.InvokeTag.doEndTag(InvokeTag.java:406)
	at cfpluginManager2ecfc1413603234$funcEXECUTESCRIPTS.runFunction(D:\home\thetidalpool.com\wwwroot\requirements\mura\plugin\pluginManager.cfc:1625)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)
	at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2483)
	at cfonRequestStart_include2ecfm2010686555._factor2(D:\home\thetidalpool.com\wwwroot\config\appcfc\onRequestStart_include.cfm:279)
	at cfonRequestStart_include2ecfm2010686555.runPage(D:\home\thetidalpool.com\wwwroot\config\appcfc\onRequestStart_include.cfm:1)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:246)
	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:736)
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:572)
	at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:3000)
	at cfApplication2ecfc385786827$funcONREQUESTSTART.runFunction(D:\home\thetidalpool.com\wwwroot\admin\Application.cfc:169)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
	at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
	at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
	at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
	at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
	at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)
	at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)
	at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:108)
	at coldfusion.runtime.AppEventInvoker.onRequestStart(AppEventInvoker.java:279)
	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:463)
	at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:42)
	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
	at coldfusion.filter.PathFilter.invoke(PathFilter.java:153)
	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:58)
	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
	at coldfusion.CfmServlet.service(CfmServlet.java:219)
	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:288)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:285)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:320)
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:175)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:297)
	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:191)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:187)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:186)
	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
	at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:288)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:285)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:320)
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:260)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:237)
	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:191)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:187)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:186)
	at com.seefusion.Filter.doFilter(Filter.java:49)
	at com.seefusion.SeeFusion.doFilter(SeeFusion.java:1500)
	at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:288)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:285)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:320)
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:260)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:237)
	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:191)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:187)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:186)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:450)
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:197)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
 

Column: 0
ID: CF_STRUCTBEAN
Line: 67
Raw Trace: at cfJavaProxy2ecfc337695686$funcINIT.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\antisamy\lib\javaloader\JavaProxy.cfc:67)
Template: D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\antisamy\lib\javaloader\JavaProxy.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 69
Raw Trace: at cfJavaLoader2ecfc287609260$funcINIT.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\antisamy\lib\javaloader\JavaLoader.cfc:69)
Template: D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\antisamy\lib\javaloader\JavaLoader.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 18
Raw Trace: at cfHibachiUtilityService2ecfc1855791383._factor0(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\HibachiUtilityService.cfc:18)
Template: D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\HibachiUtilityService.cfc
Type: CFML

Column: 0
ID: CF_HIBACHIUTILITYSERVICE
Line: 5
Raw Trace: at cfHibachiUtilityService2ecfc1855791383._factor18(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\HibachiUtilityService.cfc:5)
Template: D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\HibachiUtilityService.cfc
Type: CFML

Column: 0
ID: CF_HIBACHIUTILITYSERVICE
Line: 1
Raw Trace: at cfHibachiUtilityService2ecfc1855791383.runPage(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\HibachiUtilityService.cfc:1)
Template: D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\HibachiUtilityService.cfc
Type: CFML

Column: 0
ID: CF_CFPAGE
Line: 198
Raw Trace: at cfioc2ecfc617699991$funcCACHABLE.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\DI1\ioc.cfc:198)
Template: D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\DI1\ioc.cfc
Type: CFML

Column: 0
ID: CF_UDFMETHOD
Line: 464
Raw Trace: at cfioc2ecfc617699991$funcRESOLVEBEANCREATE.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\DI1\ioc.cfc:464)
Template: D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\DI1\ioc.cfc
Type: CFML

Column: 0
ID: CF_UDFMETHOD
Line: 494
Raw Trace: at cfioc2ecfc617699991$funcRESOLVEBEANCREATE.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\DI1\ioc.cfc:494)
Template: D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\DI1\ioc.cfc
Type: CFML

Column: 0
ID: CF_UDFMETHOD
Line: 438
Raw Trace: at cfioc2ecfc617699991$funcRESOLVEBEAN.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\DI1\ioc.cfc:438)
Template: D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\DI1\ioc.cfc
Type: CFML

Column: 0
ID: CF_UDFMETHOD
Line: 80
Raw Trace: at cfioc2ecfc617699991$funcGETBEAN.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\DI1\ioc.cfc:80)
Template: D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\DI1\ioc.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 34
Raw Trace: at cfHibachiObject2ecfc1720666238$funcGETBEAN.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\HibachiObject.cfc:34)
Template: D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\HibachiObject.cfc
Type: CFML

Column: 0
ID: CF_UDFMETHOD
Line: 40
Raw Trace: at cfHibachiObject2ecfc1720666238$funcGETSERVICE.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\HibachiObject.cfc:40)
Template: D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\HibachiObject.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 647
Raw Trace: at cfHibachi2ecfc1314475297$funcVERIFYAPPLICATIONSETUP.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\Hibachi.cfc:647)
Template: D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\Hibachi.cfc
Type: CFML

Column: 0
ID: CF_UDFMETHOD
Line: 211
Raw Trace: at cfHibachi2ecfc1314475297$funcSETUPGLOBALREQUEST.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\Hibachi.cfc:211)
Template: D:\home\thetidalpool.com\wwwroot\Slatwall\org\Hibachi\Hibachi.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 73
Raw Trace: at cfHandler2ecfc1562055548$funcVERIFYSLATWALLREQUEST.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\integrationServices\mura\model\handler\Handler.cfc:73)
Template: D:\home\thetidalpool.com\wwwroot\Slatwall\integrationServices\mura\model\handler\Handler.cfc
Type: CFML

Column: 0
ID: CF_UDFMETHOD
Line: 494
Raw Trace: at cfMuraEventHandler2ecfc1759258189$funcONGLOBALREQUESTSTART.runFunction(D:\home\thetidalpool.com\wwwroot\Slatwall\integrationServices\mura\model\handler\MuraEventHandler.cfc:494)
Template: D:\home\thetidalpool.com\wwwroot\Slatwall\integrationServices\mura\model\handler\MuraEventHandler.cfc
Type: CFML

Column: 0
ID: CFINVOKE
Line: 1625
Raw Trace: at cfpluginManager2ecfc1413603234$funcEXECUTESCRIPTS.runFunction(D:\home\thetidalpool.com\wwwroot\requirements\mura\plugin\pluginManager.cfc:1625)
Template: D:\home\thetidalpool.com\wwwroot\requirements\mura\plugin\pluginManager.cfc
Type: CFML

Column: 0
ID: CF_TEMPLATEPROXY
Line: 279
Raw Trace: at cfonRequestStart_include2ecfm2010686555._factor2(D:\home\thetidalpool.com\wwwroot\config\appcfc\onRequestStart_include.cfm:279)
Template: D:\home\thetidalpool.com\wwwroot\config\appcfc\onRequestStart_include.cfm
Type: CFML

Column: 0
ID: CF_ONREQUESTSTART_INCLUDE
Line: 1
Raw Trace: at cfonRequestStart_include2ecfm2010686555.runPage(D:\home\thetidalpool.com\wwwroot\config\appcfc\onRequestStart_include.cfm:1)
Template: D:\home\thetidalpool.com\wwwroot\config\appcfc\onRequestStart_include.cfm
Type: CFML

Column: 0
ID: CFINCLUDE
Line: 169
Raw Trace: at cfApplication2ecfc385786827$funcONREQUESTSTART.runFunction(D:\home\thetidalpool.com\wwwroot\admin\Application.cfc:169)
Template: D:\home\thetidalpool.com\wwwroot\admin\Application.cfc
Type: CFML

**Comment by peterHID** [comment]
The hosting company said this 

"This issue is caused between the updated mura and certain versions of ColdFusion. I was able to fix the site by modifying the javaproxy.cfc files within the mura installation"

I am running
Site Version 7.0.6959
Core Version 7.0.6959
App Server ColdFusion (11,0,11,301867)
