### ISSUE TITLE
Issue in model/dao/OrderDAO.cfc Line: 66

### ISSUE THREAD

**Issue by MarcAckermann** [ten24/slatwall#7123]
This SQL Code is not working on MSSQL Server 2019:

Line: 66
UPDATE sworder set paymentProcessingInProgressFlag=true where orderID=<cfqueryparam cfsqltype="cf_sql_varchar" value="#arguments.orderID#" />

The column 'paymentProcessingInProgressFlag' is type tinyint. So the query code should be:

UPDATE sworder set paymentProcessingInProgressFlag=1 where orderID=<cfqueryparam cfsqltype="cf_sql_varchar" value="#arguments.orderID#"

**Comment by migueltarga** [comment]
Could you please send a PR? 

Thank you for the report!

**Comment by MarcAckermann** [comment]
Hi Miguel,

what do you mean with PR?
This is the generated Lucee error. 

Best regards,
Marc

500 Error
Invalid column name 'true'.
Datasource:skatermd
SQL:UPDATE sworder set paymentProcessingInProgressFlag=true where orderID='d225c3f6763566db0176510bdd7b051d'
Code:0
Type:database
lucee.runtime.exp.DatabaseException: Invalid column name 'true'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:332)
	at lucee.runtime.type.util.QueryUtil.execute(QueryUtil.java:327)
	at lucee.runtime.type.QueryImpl.execute(QueryImpl.java:282)
	at lucee.runtime.type.QueryImpl.<init>(QueryImpl.java:227)
	at lucee.runtime.tag.Query.executeDatasoure(Query.java:1112)
	at lucee.runtime.tag.Query._doEndTag(Query.java:686)
	at lucee.runtime.tag.Query.doEndTag(Query.java:553)
	at model.dao.orderdao_cfc$cf.udfCall2(/Slatwall/model/dao/OrderDAO.cfc:67)
	at model.dao.orderdao_cfc$cf.udfCall(/Slatwall/model/dao/OrderDAO.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:680)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1898)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
	at model.service.orderservice_cfc$cf.udfCall4(/Slatwall/model/service/OrderService.cfc:1852)
	at model.service.orderservice_cfc$cf.udfCall(/Slatwall/model/service/OrderService.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:792)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:864)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1729)
	at org.hibachi.hibachiobject_cfc$cf.udfCall3(/Slatwall/org/Hibachi/HibachiObject.cfc:159)
	at org.hibachi.hibachiobject_cfc$cf.udfCall(/Slatwall/org/Hibachi/HibachiObject.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:680)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1898)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
	at org.hibachi.hibachiservice_cfc$cf.udfCall2(/Slatwall/org/Hibachi/HibachiService.cfc:176)
	at org.hibachi.hibachiservice_cfc$cf.udfCall(/Slatwall/org/Hibachi/HibachiService.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:792)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:864)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1729)
	at org.hibachi.hibachiservice_cfc$cf.udfCall4(/Slatwall/org/Hibachi/HibachiService.cfc:767)
	at org.hibachi.hibachiservice_cfc$cf.udfCall(/Slatwall/org/Hibachi/HibachiService.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:779)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
	at org.hibachi.hibachiservice_cfc$cf.udfCall2(/Slatwall/org/Hibachi/HibachiService.cfc:440)
	at org.hibachi.hibachiservice_cfc$cf.udfCall(/Slatwall/org/Hibachi/HibachiService.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:680)
	at lucee.runtime.ComponentImpl.onMissingMethod(ComponentImpl.java:607)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:570)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1898)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
	at _public.controllers.cart_cfc$cf.udfCall2(/Slatwall/public/controllers/cart.cfc:287)
	at _public.controllers.cart_cfc$cf.udfCall(/Slatwall/public/controllers/cart.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:681)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1917)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:898)
	at lucee.runtime.functions.dynamicEvaluation.Invoke.call(Invoke.java:49)
	at org.hibachi.framework.one_cfc$cf.udfCalla(/Slatwall/org/Hibachi/framework/one.cfc:1573)
	at org.hibachi.framework.one_cfc$cf.udfCall(/Slatwall/org/Hibachi/framework/one.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:779)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
	at org.hibachi.framework.one_cfc$cf.udfCall6(/Slatwall/org/Hibachi/framework/one.cfc:888)
	at org.hibachi.framework.one_cfc$cf.udfCall(/Slatwall/org/Hibachi/framework/one.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:779)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
	at org.hibachi.hibachi_cfc$cf.udfCall3(/Slatwall/org/Hibachi/Hibachi.cfc:1247)
	at org.hibachi.hibachi_cfc$cf.udfCall(/Slatwall/org/Hibachi/Hibachi.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:680)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1898)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
	at org.hibachi.hibachiscope_cfc$cf.udfCall3(/Slatwall/org/Hibachi/HibachiScope.cfc:294)
	at org.hibachi.hibachiscope_cfc$cf.udfCall(/Slatwall/org/Hibachi/HibachiScope.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:680)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1898)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
	at integrationservices.mura.model.handler.muraeventhandler_cfc$cf.udfCall1(/Slatwall/integrationServices/mura/model/handler/MuraEventHandler.cfc:106)
	at integrationservices.mura.model.handler.muraeventhandler_cfc$cf.udfCall(/Slatwall/integrationServices/mura/model/handler/MuraEventHandler.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:681)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1912)
	at lucee.runtime.tag.Invoke.doComponent(Invoke.java:209)
	at lucee.runtime.tag.Invoke.doEndTag(Invoke.java:186)
	at plugin.pluginmanager_cfc$cf.udfCall3_000048_000052(/mura/plugin/pluginManager.cfc:1738)
	at plugin.pluginmanager_cfc$cf.udfCall3_000048(/mura/plugin/pluginManager.cfc:1728)
	at plugin.pluginmanager_cfc$cf.udfCall3(/mura/plugin/pluginManager.cfc:1583)
	at plugin.pluginmanager_cfc$cf.udfCall(/mura/plugin/pluginManager.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:792)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:864)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1729)
	at plugin.pluginmanager_cfc$cf.udfCall3(/mura/plugin/pluginManager.cfc:1275)
	at plugin.pluginmanager_cfc$cf.udfCall(/mura/plugin/pluginManager.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:680)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1898)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
	at content.contentserver_cfc$cf.udfCall2(/mura/content/contentServer.cfc:788)
	at content.contentserver_cfc$cf.udfCall(/mura/content/contentServer.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:779)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
	at content.contentserver_cfc$cf.udfCall1(/mura/content/contentServer.cfc:259)
	at content.contentserver_cfc$cf.udfCall(/mura/content/contentServer.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:779)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
	at content.contentserver_cfc$cf.udfCall1(/mura/content/contentServer.cfc:345)
	at content.contentserver_cfc$cf.udfCall(/mura/content/contentServer.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:681)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1917)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:864)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1729)
	at content.contentserver_cfc$cf.udfCall2(/mura/content/contentServer.cfc:716)
	at content.contentserver_cfc$cf.udfCall(/mura/content/contentServer.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:680)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1898)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
	at index_cfm$cf$vv.call(/index.cfm:43)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:945)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:837)
	at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:216)
	at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:42)
	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2416)
	at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2406)
	at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2381)
	at lucee.runtime.engine.Request.exe(Request.java:43)
	at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1170)
	at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1116)
	at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97)
	at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:415)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Unknown Source)

Column: 0
ID: ??
Line: 67
Raw Trace: model.dao.orderdao_cfc$cf.udfCall2(/Slatwall/model/dao/OrderDAO.cfc:67)
Template: D:\inetpub\website06\httpdoc\Slatwall\model\dao\OrderDAO.cfc
Type: cfml

Column: 0
ID: ??
Line: 1852
Raw Trace: model.service.orderservice_cfc$cf.udfCall4(/Slatwall/model/service/OrderService.cfc:1852)
Template: D:\inetpub\website06\httpdoc\Slatwall\model\service\OrderService.cfc
Type: cfml

Column: 0
ID: ??
Line: 159
Raw Trace: org.hibachi.hibachiobject_cfc$cf.udfCall3(/Slatwall/org/Hibachi/HibachiObject.cfc:159)
Template: D:\inetpub\website06\httpdoc\Slatwall\org\Hibachi\HibachiObject.cfc
Type: cfml

Column: 0
ID: ??
Line: 176
Raw Trace: org.hibachi.hibachiservice_cfc$cf.udfCall2(/Slatwall/org/Hibachi/HibachiService.cfc:176)
Template: D:\inetpub\website06\httpdoc\Slatwall\org\Hibachi\HibachiService.cfc
Type: cfml

Column: 0
ID: ??
Line: 767
Raw Trace: org.hibachi.hibachiservice_cfc$cf.udfCall4(/Slatwall/org/Hibachi/HibachiService.cfc:767)
Template: D:\inetpub\website06\httpdoc\Slatwall\org\Hibachi\HibachiService.cfc
Type: cfml

Column: 0
ID: ??
Line: 440
Raw Trace: org.hibachi.hibachiservice_cfc$cf.udfCall2(/Slatwall/org/Hibachi/HibachiService.cfc:440)
Template: D:\inetpub\website06\httpdoc\Slatwall\org\Hibachi\HibachiService.cfc
Type: cfml

Column: 0
ID: ??
Line: 287
Raw Trace: _public.controllers.cart_cfc$cf.udfCall2(/Slatwall/public/controllers/cart.cfc:287)
Template: D:\inetpub\website06\httpdoc\Slatwall\public\controllers\cart.cfc
Type: cfml

Column: 0
ID: ??
Line: 1573
Raw Trace: org.hibachi.framework.one_cfc$cf.udfCalla(/Slatwall/org/Hibachi/framework/one.cfc:1573)
Template: D:\inetpub\website06\httpdoc\Slatwall\org\Hibachi\framework\one.cfc
Type: cfml

Column: 0
ID: ??
Line: 888
Raw Trace: org.hibachi.framework.one_cfc$cf.udfCall6(/Slatwall/org/Hibachi/framework/one.cfc:888)
Template: D:\inetpub\website06\httpdoc\Slatwall\org\Hibachi\framework\one.cfc
Type: cfml

Column: 0
ID: ??
Line: 1247
Raw Trace: org.hibachi.hibachi_cfc$cf.udfCall3(/Slatwall/org/Hibachi/Hibachi.cfc:1247)
Template: D:\inetpub\website06\httpdoc\Slatwall\org\Hibachi\Hibachi.cfc
Type: cfml

Column: 0
ID: ??
Line: 294
Raw Trace: org.hibachi.hibachiscope_cfc$cf.udfCall3(/Slatwall/org/Hibachi/HibachiScope.cfc:294)
Template: D:\inetpub\website06\httpdoc\Slatwall\org\Hibachi\HibachiScope.cfc
Type: cfml

Column: 0
ID: ??
Line: 106
Raw Trace: integrationservices.mura.model.handler.muraeventhandler_cfc$cf.udfCall1(/Slatwall/integrationServices/mura/model/handler/MuraEventHandler.cfc:106)
Template: D:\inetpub\website06\httpdoc\Slatwall\integrationServices\mura\model\handler\MuraEventHandler.cfc
Type: cfml

Column: 0
ID: ??
Line: 1738
Raw Trace: plugin.pluginmanager_cfc$cf.udfCall3_000048_000052(/mura/plugin/pluginManager.cfc:1738)
Template: D:\inetpub\website06\httpdoc\core\mura\plugin\pluginManager.cfc
Type: cfml

Column: 0
ID: ??
Line: 1728
Raw Trace: plugin.pluginmanager_cfc$cf.udfCall3_000048(/mura/plugin/pluginManager.cfc:1728)
Template: D:\inetpub\website06\httpdoc\core\mura\plugin\pluginManager.cfc
Type: cfml

Column: 0
ID: ??
Line: 1583
Raw Trace: plugin.pluginmanager_cfc$cf.udfCall3(/mura/plugin/pluginManager.cfc:1583)
Template: D:\inetpub\website06\httpdoc\core\mura\plugin\pluginManager.cfc
Type: cfml

Column: 0
ID: ??
Line: 1275
Raw Trace: plugin.pluginmanager_cfc$cf.udfCall3(/mura/plugin/pluginManager.cfc:1275)
Template: D:\inetpub\website06\httpdoc\core\mura\plugin\pluginManager.cfc
Type: cfml

Column: 0
ID: ??
Line: 788
Raw Trace: content.contentserver_cfc$cf.udfCall2(/mura/content/contentServer.cfc:788)
Template: D:\inetpub\website06\httpdoc\core\mura\content\contentServer.cfc
Type: cfml

Column: 0
ID: ??
Line: 259
Raw Trace: content.contentserver_cfc$cf.udfCall1(/mura/content/contentServer.cfc:259)
Template: D:\inetpub\website06\httpdoc\core\mura\content\contentServer.cfc
Type: cfml

Column: 0
ID: ??
Line: 345
Raw Trace: content.contentserver_cfc$cf.udfCall1(/mura/content/contentServer.cfc:345)
Template: D:\inetpub\website06\httpdoc\core\mura\content\contentServer.cfc
Type: cfml

Column: 0
ID: ??
Line: 716
Raw Trace: content.contentserver_cfc$cf.udfCall2(/mura/content/contentServer.cfc:716)
Template: D:\inetpub\website06\httpdoc\core\mura\content\contentServer.cfc
Type: cfml

Column: 0
ID: ??
Line: 43
Raw Trace: index_cfm$cf$vv.call(/index.cfm:43)
Template: D:\inetpub\website06\httpdoc\index.cfm
Type: cfml
