### ISSUE TITLE
Event product order breaks because of issue in model/dao/WorkflowDAO.cfc

### ISSUE THREAD

**Issue by MarcAckermann** [ten24/slatwall#7124]
Issue in model/dao/WorkflowDAO.cfc Line 90:

		<cfreturn ORMExecuteQuery('SELECT new map(t.workflowTriggerID as workflowTriggerID, t.timeout as timeout)
								   FROM	SlatwallWorkflowTrigger t 
								   WHERE runningFlag=true') />

Working SQL code would be :
 WHERE runningFlag = 1

Running on MSSQL and Lucee.

The thrown Lucee Error:

500 Error
could not execute query
SQL:select slatwallwo0_.workflowTriggerID as workflow1_1679_, slatwallwo0_.triggerType as triggerT2_1679_, slatwallwo0_.objectPropertyIdentifier as objectPr3_1679_, slatwallwo0_.triggerEvent as triggerE4_1679_, slatwallwo0_.triggerEventTitle as triggerE5_1679_, slatwallwo0_.saveTriggerHistoryFlag as saveTrig6_1679_, slatwallwo0_.runningFlag as runningF7_1679_, slatwallwo0_.nextRunDateTime as nextRunD8_1679_, slatwallwo0_.startDateTime as startDat9_1679_, slatwallwo0_.endDateTime as endDate10_1679_, slatwallwo0_.collectionFetchSize as collect11_1679_, slatwallwo0_.collectionPassthrough as collect12_1679_, slatwallwo0_.timeout as timeout1679_, slatwallwo0_.scheduleCollectionConfig as schedul14_1679_, slatwallwo0_.remoteID as remoteID1679_, slatwallwo0_.createdDateTime as created16_1679_, slatwallwo0_.createdByAccountID as created17_1679_, slatwallwo0_.modifiedDateTime as modifie18_1679_, slatwallwo0_.modifiedByAccountID as modifie19_1679_, slatwallwo0_.scheduleID as scheduleID1679_, slatwallwo0_.scheduleCollectionID as schedul21_1679_, slatwallwo0_.workflowID as workflowID1679_ from SwWorkflowTrigger slatwallwo0_ left outer join SwWorkflow slatwallwo1_ on slatwallwo0_.workflowID=slatwallwo1_.workflowID where slatwallwo0_.triggerEvent=? and slatwallwo1_.activeFlag=1 group by slatwallwo0_.workflowTriggerID
Code:8120
Type:org.hibernate.exception.SQLGrammarException
lucee.runtime.exp.NativeException: could not execute query
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:92)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
	at org.hibernate.loader.Loader.doList(Loader.java:2452)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2192)
	at org.hibernate.loader.Loader.list(Loader.java:2187)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:452)
	at org.hibernate.hql.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:363)
	at org.hibernate.engine.query.HQLQueryPlan.performList(HQLQueryPlan.java:196)
	at org.hibernate.impl.SessionImpl.list(SessionImpl.java:1258)
	at org.hibernate.impl.QueryImpl.list(QueryImpl.java:102)
	at org.lucee.extension.orm.hibernate.HibernateORMSession.__executeQuery(HibernateORMSession.java:490)
	at org.lucee.extension.orm.hibernate.HibernateORMSession._executeQuery(HibernateORMSession.java:348)
	at org.lucee.extension.orm.hibernate.HibernateORMSession.executeQuery(HibernateORMSession.java:338)
	at lucee.runtime.functions.orm.ORMExecuteQuery._call(ORMExecuteQuery.java:71)
	at lucee.runtime.functions.orm.ORMExecuteQuery.call(ORMExecuteQuery.java:47)
	at model.dao.workflowdao_cfc$cf.udfCall(/Slatwall/model/dao/WorkflowDAO.cfc:83)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:681)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1917)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:864)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1729)
	at model.service.workflowservice_cfc$cf.udfCall1(/Slatwall/model/service/WorkflowService.cfc:134)
	at model.service.workflowservice_cfc$cf.udfCall(/Slatwall/model/service/WorkflowService.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:681)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1917)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:864)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1729)
	at model.handler.hibachieventhandler_cfc$cf.udfCall(/Slatwall/model/handler/HibachiEventHandler.cfc:9)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:681)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1917)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:864)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1729)
	at org.hibachi.hibachieventservice_cfc$cf.udfCall1(/Slatwall/org/Hibachi/HibachiEventService.cfc:100)
	at org.hibachi.hibachieventservice_cfc$cf.udfCall(/Slatwall/org/Hibachi/HibachiEventService.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:680)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1898)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
	at org.hibachi.hibachiservice_cfc$cf.udfCall2(/Slatwall/org/Hibachi/HibachiService.cfc:186)
	at org.hibachi.hibachiservice_cfc$cf.udfCall(/Slatwall/org/Hibachi/HibachiService.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:792)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:864)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1729)
	at org.hibachi.hibachiservice_cfc$cf.udfCall4(/Slatwall/org/Hibachi/HibachiService.cfc:767)
	at org.hibachi.hibachiservice_cfc$cf.udfCall(/Slatwall/org/Hibachi/HibachiService.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:779)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
	at org.hibachi.hibachiservice_cfc$cf.udfCall2(/Slatwall/org/Hibachi/HibachiService.cfc:440)
	at org.hibachi.hibachiservice_cfc$cf.udfCall(/Slatwall/org/Hibachi/HibachiService.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:680)
	at lucee.runtime.ComponentImpl.onMissingMethod(ComponentImpl.java:607)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:570)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1898)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
	at _public.controllers.cart_cfc$cf$250.udfCall2(/Slatwall/public/controllers/cart.cfc:287)
	at _public.controllers.cart_cfc$cf$250.udfCall(/Slatwall/public/controllers/cart.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:681)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1917)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:898)
	at lucee.runtime.functions.dynamicEvaluation.Invoke.call(Invoke.java:49)
	at org.hibachi.framework.one_cfc$cf.udfCalla(/Slatwall/org/Hibachi/framework/one.cfc:1573)
	at org.hibachi.framework.one_cfc$cf.udfCall(/Slatwall/org/Hibachi/framework/one.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:779)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
	at org.hibachi.framework.one_cfc$cf.udfCall6(/Slatwall/org/Hibachi/framework/one.cfc:888)
	at org.hibachi.framework.one_cfc$cf.udfCall(/Slatwall/org/Hibachi/framework/one.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:779)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
	at org.hibachi.hibachi_cfc$cf.udfCall3(/Slatwall/org/Hibachi/Hibachi.cfc:1247)
	at org.hibachi.hibachi_cfc$cf.udfCall(/Slatwall/org/Hibachi/Hibachi.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:680)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1898)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
	at org.hibachi.hibachiscope_cfc$cf.udfCall3(/Slatwall/org/Hibachi/HibachiScope.cfc:294)
	at org.hibachi.hibachiscope_cfc$cf.udfCall(/Slatwall/org/Hibachi/HibachiScope.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:680)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1898)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
	at integrationservices.mura.model.handler.muraeventhandler_cfc$cf.udfCall1(/Slatwall/integrationServices/mura/model/handler/MuraEventHandler.cfc:106)
	at integrationservices.mura.model.handler.muraeventhandler_cfc$cf.udfCall(/Slatwall/integrationServices/mura/model/handler/MuraEventHandler.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:681)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1912)
	at lucee.runtime.tag.Invoke.doComponent(Invoke.java:209)
	at lucee.runtime.tag.Invoke.doEndTag(Invoke.java:186)
	at plugin.pluginmanager_cfc$cf.udfCall3_000048_000052(/mura/plugin/pluginManager.cfc:1738)
	at plugin.pluginmanager_cfc$cf.udfCall3_000048(/mura/plugin/pluginManager.cfc:1728)
	at plugin.pluginmanager_cfc$cf.udfCall3(/mura/plugin/pluginManager.cfc:1583)
	at plugin.pluginmanager_cfc$cf.udfCall(/mura/plugin/pluginManager.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:792)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:864)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1729)
	at plugin.pluginmanager_cfc$cf.udfCall3(/mura/plugin/pluginManager.cfc:1275)
	at plugin.pluginmanager_cfc$cf.udfCall(/mura/plugin/pluginManager.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:680)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1898)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
	at content.contentserver_cfc$cf.udfCall2(/mura/content/contentServer.cfc:788)
	at content.contentserver_cfc$cf.udfCall(/mura/content/contentServer.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:779)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
	at content.contentserver_cfc$cf.udfCall1(/mura/content/contentServer.cfc:259)
	at content.contentserver_cfc$cf.udfCall(/mura/content/contentServer.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:779)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
	at content.contentserver_cfc$cf.udfCall1(/mura/content/contentServer.cfc:345)
	at content.contentserver_cfc$cf.udfCall(/mura/content/contentServer.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:681)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1917)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:864)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1729)
	at content.contentserver_cfc$cf.udfCall2(/mura/content/contentServer.cfc:716)
	at content.contentserver_cfc$cf.udfCall(/mura/content/contentServer.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:680)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1898)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
	at index_cfm$cf$26j.call(/index.cfm:43)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:945)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:837)
	at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:216)
	at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:42)
	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2416)
	at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2406)
	at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2381)
	at lucee.runtime.engine.Request.exe(Request.java:43)
	at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1170)
	at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1116)
	at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97)
	at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:415)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.hibernate.exception.SQLGrammarException: could not execute query
	... 227 more
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Column 'SwWorkflowTrigger.triggerType' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
	at org.hibernate.jdbc.AbstractBatcher.getResultSet(AbstractBatcher.java:208)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:1869)
	at org.hibernate.loader.Loader.doQuery(Loader.java:718)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:270)
	at org.hibernate.loader.Loader.doList(Loader.java:2449)
	... 224 more

Column: 0
ID: ??
Line: 83
Raw Trace: model.dao.workflowdao_cfc$cf.udfCall(/Slatwall/model/dao/WorkflowDAO.cfc:83)
Template: D:\inetpub\website06\httpdoc\Slatwall\model\dao\WorkflowDAO.cfc
Type: cfml

Column: 0
ID: ??
Line: 134
Raw Trace: model.service.workflowservice_cfc$cf.udfCall1(/Slatwall/model/service/WorkflowService.cfc:134)
Template: D:\inetpub\website06\httpdoc\Slatwall\model\service\WorkflowService.cfc
Type: cfml

Column: 0
ID: ??
Line: 9
Raw Trace: model.handler.hibachieventhandler_cfc$cf.udfCall(/Slatwall/model/handler/HibachiEventHandler.cfc:9)
Template: D:\inetpub\website06\httpdoc\Slatwall\model\handler\HibachiEventHandler.cfc
Type: cfml

Column: 0
ID: ??
Line: 100
Raw Trace: org.hibachi.hibachieventservice_cfc$cf.udfCall1(/Slatwall/org/Hibachi/HibachiEventService.cfc:100)
Template: D:\inetpub\website06\httpdoc\Slatwall\org\Hibachi\HibachiEventService.cfc
Type: cfml

Column: 0
ID: ??
Line: 186
Raw Trace: org.hibachi.hibachiservice_cfc$cf.udfCall2(/Slatwall/org/Hibachi/HibachiService.cfc:186)
Template: D:\inetpub\website06\httpdoc\Slatwall\org\Hibachi\HibachiService.cfc
Type: cfml

Column: 0
ID: ??
Line: 767
Raw Trace: org.hibachi.hibachiservice_cfc$cf.udfCall4(/Slatwall/org/Hibachi/HibachiService.cfc:767)
Template: D:\inetpub\website06\httpdoc\Slatwall\org\Hibachi\HibachiService.cfc
Type: cfml

Column: 0
ID: ??
Line: 440
Raw Trace: org.hibachi.hibachiservice_cfc$cf.udfCall2(/Slatwall/org/Hibachi/HibachiService.cfc:440)
Template: D:\inetpub\website06\httpdoc\Slatwall\org\Hibachi\HibachiService.cfc
Type: cfml

Column: 0
ID: ??
Line: 287
Raw Trace: _public.controllers.cart_cfc$cf$250.udfCall2(/Slatwall/public/controllers/cart.cfc:287)
Template: D:\inetpub\website06\httpdoc\Slatwall\public\controllers\cart.cfc
Type: cfml

Column: 0
ID: ??
Line: 1573
Raw Trace: org.hibachi.framework.one_cfc$cf.udfCalla(/Slatwall/org/Hibachi/framework/one.cfc:1573)
Template: D:\inetpub\website06\httpdoc\Slatwall\org\Hibachi\framework\one.cfc
Type: cfml

Column: 0
ID: ??
Line: 888
Raw Trace: org.hibachi.framework.one_cfc$cf.udfCall6(/Slatwall/org/Hibachi/framework/one.cfc:888)
Template: D:\inetpub\website06\httpdoc\Slatwall\org\Hibachi\framework\one.cfc
Type: cfml

Column: 0
ID: ??
Line: 1247
Raw Trace: org.hibachi.hibachi_cfc$cf.udfCall3(/Slatwall/org/Hibachi/Hibachi.cfc:1247)
Template: D:\inetpub\website06\httpdoc\Slatwall\org\Hibachi\Hibachi.cfc
Type: cfml

Column: 0
ID: ??
Line: 294
Raw Trace: org.hibachi.hibachiscope_cfc$cf.udfCall3(/Slatwall/org/Hibachi/HibachiScope.cfc:294)
Template: D:\inetpub\website06\httpdoc\Slatwall\org\Hibachi\HibachiScope.cfc
Type: cfml

Column: 0
ID: ??
Line: 106
Raw Trace: integrationservices.mura.model.handler.muraeventhandler_cfc$cf.udfCall1(/Slatwall/integrationServices/mura/model/handler/MuraEventHandler.cfc:106)
Template: D:\inetpub\website06\httpdoc\Slatwall\integrationServices\mura\model\handler\MuraEventHandler.cfc
Type: cfml

Column: 0
ID: ??
Line: 1738
Raw Trace: plugin.pluginmanager_cfc$cf.udfCall3_000048_000052(/mura/plugin/pluginManager.cfc:1738)
Template: D:\inetpub\website06\httpdoc\core\mura\plugin\pluginManager.cfc
Type: cfml

Column: 0
ID: ??
Line: 1728
Raw Trace: plugin.pluginmanager_cfc$cf.udfCall3_000048(/mura/plugin/pluginManager.cfc:1728)
Template: D:\inetpub\website06\httpdoc\core\mura\plugin\pluginManager.cfc
Type: cfml

Column: 0
ID: ??
Line: 1583
Raw Trace: plugin.pluginmanager_cfc$cf.udfCall3(/mura/plugin/pluginManager.cfc:1583)
Template: D:\inetpub\website06\httpdoc\core\mura\plugin\pluginManager.cfc
Type: cfml

Column: 0
ID: ??
Line: 1275
Raw Trace: plugin.pluginmanager_cfc$cf.udfCall3(/mura/plugin/pluginManager.cfc:1275)
Template: D:\inetpub\website06\httpdoc\core\mura\plugin\pluginManager.cfc
Type: cfml

Column: 0
ID: ??
Line: 788
Raw Trace: content.contentserver_cfc$cf.udfCall2(/mura/content/contentServer.cfc:788)
Template: D:\inetpub\website06\httpdoc\core\mura\content\contentServer.cfc
Type: cfml

Column: 0
ID: ??
Line: 259
Raw Trace: content.contentserver_cfc$cf.udfCall1(/mura/content/contentServer.cfc:259)
Template: D:\inetpub\website06\httpdoc\core\mura\content\contentServer.cfc
Type: cfml

Column: 0
ID: ??
Line: 345
Raw Trace: content.contentserver_cfc$cf.udfCall1(/mura/content/contentServer.cfc:345)
Template: D:\inetpub\website06\httpdoc\core\mura\content\contentServer.cfc
Type: cfml

Column: 0
ID: ??
Line: 716
Raw Trace: content.contentserver_cfc$cf.udfCall2(/mura/content/contentServer.cfc:716)
Template: D:\inetpub\website06\httpdoc\core\mura\content\contentServer.cfc
Type: cfml

Column: 0
ID: ??
Line: 43
Raw Trace: index_cfm$cf$26j.call(/index.cfm:43)
Template: D:\inetpub\website06\httpdoc\index.cfm
Type: cfml

**Comment by MarcAckermann** [comment]
Looks like there are alot of todo's and code fixes needed in the WorkflowDAO.cfc.

Because of this the order/checkout process of products that are type 'Events' are currently not possible.
